### ISSUE TITLE
Git missing

### ISSUE THREAD

**Issue by a16bitsysop** [ludeeus/dockerfile-updater#38]
## The problem

Action runs but fails as git is missing

```
/action/run.sh: line 3: git: command not found
7
I solemnly swear that I am up to no good.
8
/action/run.sh: line 10: git: command not found
9
/action/run.sh: line 11: git: command not found
10
/action/run.sh: line 14: git: command not found
11
Traceback (most recent call last):
12
  File "/action/run.py", line 4, in <module>
13
    from .config import Config
14
ImportError: attempted relative import with no known parent package
```

Also for example manual trigger could be added eg:

```
name: Update Dependencies

on:
  schedule:
    - cron:  '40 16 * * *'
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
      logLevel:
        description: 'The Logging Level'
        required: false
        default: 'low'

jobs:
  #allow editing of manual running parameters
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Deploy Environment: ${{ github.event.inputs.deployEnvironment }}"
        echo "Log Level: ${{ github.event.inputs.logLevel }}"

  deploy:
    name: Update Dockerfiles etc
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v2

      - name: 📤 Update Dockerfiles
        uses: ludeeus/dockerfile-updater@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

## Environment

- Link to action configuration:
- no extra confit used
- Link to action run:
Pasted above
## Additional information
